services:
  mysql:
    image: mysql:8.4
    container_name: atividade-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: atividade_db
      MYSQL_USER: aluno
      MYSQL_PASSWORD: aluno123
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - rede_atividade
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot123"]
      interval: 10s
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin:5.2-apache
    container_name: atividade-phpmyadmin
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 0
    ports:
      - "8080:80"
    networks:
      - rede_atividade

volumes:
  mysql_data:

networks:
  rede_atividade:
    driver: bridge
